Tests
fgriff/online-store pull request #16
Opened 2023-01-11 16:32 UTC by fgriff

Добавили тестов

2023-01-12 08:37 UTC, wayjewish reviewed
сами тесты жесткие конечно
ни один из них не тестирует какую либо функциональность 
например:
клик по кнопке добавить -> изменилась цена, кол-во в шапке
отправили форму с пустыми полями -> чек ошибок валидации от каждого поля
отправили полную форму -> получили сообщение о успехе

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/BasketCart.test.tsx
> +    const product = {
тип

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/BasketCart.test.tsx
> +    const card = {
тип

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/BasketCart.test.tsx
> +      <Provider store={store}>
зачем стор?

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/BasketCart.test.tsx
> +      { wrapper: BrowserRouter },
зачем роутер?

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/FormProductRegistration.test.tsx
> +      <Provider store={store}>
стор?

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/FormProductRegistration.test.tsx
> +        {wrapper: BrowserRouter}
роутер?

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/GoodsCard.test.tsx
> +    const data = {
тип

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/GoodsCard.test.tsx
> +    const layout = 'grid';
тип

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/FormProductRegistration.test.tsx
> +      <Provider store={store}>
и далее

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/FormProductRegistration.test.tsx
> +        {wrapper: BrowserRouter}
и далее

2023-01-12 08:37 UTC, wayjewish commented on online-store/__tests__/GoodsCard.test.tsx
> +    const layout = 'grid';
и далее

2023-01-13 19:41 UTC, fgriff commented on online-store/__tests__/GoodsCard.test.tsx
> +    const layout = 'grid';
Добавил тип

2023-01-13 19:41 UTC, fgriff commented on online-store/__tests__/GoodsCard.test.tsx
> +    const data = {
Добавил тип

2023-01-13 19:41 UTC, fgriff commented on online-store/__tests__/FormProductRegistration.test.tsx
> +        {wrapper: BrowserRouter}
Без Provider и BrowserRouter падает ошибка

2023-01-13 19:41 UTC, fgriff commented on online-store/__tests__/FormProductRegistration.test.tsx
> +      <Provider store={store}>
Без Provider и BrowserRouter падает ошибка

2023-01-13 19:41 UTC, fgriff commented on online-store/__tests__/BasketCart.test.tsx
> +      { wrapper: BrowserRouter },
Удалил BrowserRouter

2023-01-13 19:41 UTC, fgriff commented on online-store/__tests__/BasketCart.test.tsx
> +      <Provider store={store}>
Удалил Provider

2023-01-13 19:42 UTC, fgriff commented on online-store/__tests__/BasketCart.test.tsx
> +    const card = {
Добавил тип

2023-01-13 19:42 UTC, fgriff commented on online-store/__tests__/BasketCart.test.tsx
> +    const product = {
Добавил тип

2023-01-15 10:31 UTC, fgriff commented on online-store/__tests__/FormProductRegistration.test.tsx
> +      <Provider store={store}>
![image](https://user-images.githubusercontent.com/63111926/212535675-f4db01a5-46e1-49db-81a8-3e61877f9b1d.png)

2023-01-15 10:31 UTC, fgriff commented on online-store/__tests__/FormProductRegistration.test.tsx
> +        {wrapper: BrowserRouter}
![image](https://user-images.githubusercontent.com/63111926/212535704-2bb3e0a3-53aa-4655-b71f-02f2929bae88.png)

2023-01-15 13:01 UTC, fgriff commented on online-store/__tests__/FormProductRegistration.test.tsx
> +        {wrapper: BrowserRouter}
Добавил тест для проверки правильности заполнения полей формы покупки

2023-01-17 10:10 UTC, wayjewish requested changes
на счет стора и роутера над утонить будет
но я вижу многие подключают и забивают)

2023-01-17 10:10 UTC, wayjewish commented on online-store/__tests__/FormProductRegistration.test.tsx
> +    await waitFor(() => {
поправь варнинг
![Снимок экрана 2023-01-17 125759](https://user-images.githubusercontent.com/52935522/212868446-8ee2f922-d5bb-4ecb-aa2f-8488b5258cab.png)

и waitFor здесь не нужен, тут как раз таки act

2023-01-17 10:10 UTC, wayjewish commented on online-store/__tests__/GoodsCard.test.tsx
> +    render(
поправь варнинг
![Снимок экрана 2023-01-17 125741](https://user-images.githubusercontent.com/52935522/212869573-1ce4f656-f6ce-40c2-ad3b-77ef83504852.png)

2023-01-17 10:10 UTC, wayjewish commented on online-store/__tests__/FormProductRegistration.test.tsx
> +    await waitFor(() => {
кста из за этого waitFor тест не правильно работает
сделаешь через act увидишь почему)

2023-01-17 10:11 UTC, wayjewish commented on online-store/__tests__/FormProductRegistration.test.tsx
> +      <Provider store={store}>
пусть останется как есть пока что

2023-01-17 10:12 UTC, wayjewish commented on online-store/__tests__/FormProductRegistration.test.tsx
> +        {wrapper: BrowserRouter}
оставляй

2023-01-17 10:14 UTC, wayjewish commented on online-store/__tests__/FormProductRegistration.test.tsx
> +    await waitFor(() => {
уточни на счет fireEvent там есть фишка чтоб изменения компонента найти это асинхронная история
но дока лучше меня расскажет

2023-01-18 17:09 UTC, fgriff commented on online-store/__tests__/GoodsCard.test.tsx
> +    render(
Пофиксил ошибку

2023-01-28 11:51 UTC, fgriff commented on online-store/__tests__/FormProductRegistration.test.tsx
> +    await waitFor(() => {
Пофиксил ошибку, использовал act

2023-01-28 11:57 UTC, fgriff commented on online-store/__tests__/FormProductRegistration.test.tsx
> +    await waitFor(() => {
Не нашел такого. Наткнулся в репе реакта на их тест с act, сделал по аналогии, все заработало. А так да - простая замена waitFor на act ломает тест, он не может найти элементы, которые рендерятся, если не проходит валидация

2023-01-29 10:00 UTC, wayjewish approved these changes

2023-01-29 10:35 UTC, IvanBusygin approved these changes

2023-01-29 10:43 UTC, merged